### ISSUE TITLE
Custom databases? 

### ISSUE THREAD

**Issue by ebueren** [iquasere/reCOGnizer#14]
Hello! I am curious about the --custom-database option in the Recognizer help. Is it possible for users to include additional specific Hmm profiles? 

I am very much a novice at database building, so I haven't been able to employ --custom-database correctly or figure out what format and metadata is necessary to successfully run this, but it would be amazing if I could incorporate other databases! I would appreciate any guidance!

**Comment by iquasere** [comment]
Hey there! I'm on vacations now, but will be back in two weeks. Will take a look at this when I get back, cheers

**Comment by iquasere** [comment]
As it stands now, using the "custom database" workflow with reCOGnizer doesn't offer much advantage over using `rpsblast` directly. However, I should really fix this, and might do it in the next weeks if there is an interest in it.

Originally, the idea was simply to use the multithreaded capability of reCOGnizer, since the tool itself splits the input into several files to accelerate annotation. However, since using a custom database, reCOGnizer will only output the BLAST results themselves, and not be of more assistance (i.e., retrieving further information from results).

If you have the HMM profiles already, first you have to create an HMM database specifically for `rpsblast`. You can do this by building a PN file, e.g., `db1.pn` in the format
```
/path/to/profile1.smp
/path/to/profile2.smp
```
and running `makeprofiledb -in db1.pn -title db1 -out path/to/db1 -max_smp_vol 1000000`. Then, you can run `recognizer -f input.fasta -db path/to/db1 --custom-database [other parameters]`.

Do note that at this time this annotation won't be multithreaded because I checked the code and it wasn't updated for a long time. I'm going to fix that, and should soon have a version where it's working properly.

**Comment by iquasere** [comment]
If you have any more questions, don't hesitate following on this issue or raising a new one!  Hope this info was useful!
